### ISSUE TITLE
Bug 25/02/2019

### ISSUE THREAD

**Issue by sam-dyer** [TheMasterCado/ParkitectPeepCam#1]
NullReferenceException: Object reference not set to an instance of an object
PeepCam.PlayableGuest.Update () (at <678c9c1e39cd46dca85968ca77f2b46d>:0)

Error Message: There has been an error that may be caused by mods.
Please contact the <b>mod's author</b>.

These mods seem to be broken (there might be more):
PeepCam (TheMasterCado@PeepCam)

Operating System: Windows 10  (10.0.0) 64bit
Game Version: Version 1.3
Scenario Editor: False

Mods:
Distants Support Set v1 (com.themeparkitect.Distants Support Set v1), enabled
Retro Steel Coaster (Marnit@ParkitectRetroSteelCoaster), enabled
Support Pack (com.themeparkitect.Support Pack), disabled
Extra Lights (com.themeparkitect.Extra Lights), enabled
PTE (com.themeparkitect.PTE), enabled
Picnic Pack (com.themeparkitect.Picnic Pack), enabled
Castle Kit (com.themeparkitect.Castle Kit), enabled
PathCovers+ (com.themeparkitect.PathCovers+), enabled
Catwalks (com.themeparkitect.Catwalks), enabled
Cyberpunkland (com.themeparkitect.Cyberpunkland), enabled
Letters (com.themeparkitect.Letters), enabled
Building Kit (com.themeparkitect.Building Kit), enabled
Effects Kit (com.themeparkitect.Effects Kit), enabled
CTS (com.themeparkitect.CTS), enabled
Coaster Anarchy (Marnit@ParkitectCoasterAnarchy), disabled
Neon Kit (com.themeparkitect.Neon Kit), enabled
Razevil Building Set (com.themeparkitect.Razevil Building Set), enabled
shyguy's Building Set 4 (com.themeparkitect.shyguy's Building Set 4), enabled
Cars Pack (com.themeparkitect.Cars Pack), enabled
shyguy's Building Set 1 (com.themeparkitect.shyguy's Building Set 1), enabled
shyguy's Building Set 2 (com.themeparkitect.shyguy's Building Set 2), enabled
Station Covers (com.themeparkitect.Station Covers), enabled
Architect toolbox (com.themeparkitect.Architect toolbox), enabled
Toys Kit (com.themeparkitect.Toys Kit), enabled
Windoors (com.themeparkitect.Windoors), enabled
Maya (com.themeparkitect.Maya), enabled
Asia Pack (com.themeparkitect.Asia Pack), enabled
shyguy's Buildings Set 3 (com.themeparkitect.shyguy's Buildings Set 3), enabled
Fence Assortment Pack (com.themeparkitect.Fence Assortment Pack), enabled
shyguy's Dining Set (com.themeparkitect.shyguy's Dining Set), enabled
Basic Windows (com.themeparkitect.Basic Windows), enabled
Neolithic pack (com.themeparkitect.Neolithic pack), enabled
Construction Anarchy (Marnit@ParkitectAnarchy), enabled
Perspective Camera (H-POPS@PerspectiveCamera), disabled
CoasterCam (H-POPS@CoasterCam), enabled
More Realism (TheMasterCado@MoreRealism), enabled
Quadruple Rail Coaster (Marnit@ParkitectQuadRailCoaster), enabled
Side Friction Coaster (SideFrictionCoaster), disabled
Panda Entertainer (PandaEntertainer), disabled
Virginia Reel (VirginiaReel), disabled
Corkscrew Coaster (CorkscrewCoaster), disabled
RoadWorks (com.themeparkitect.RoadWorks), enabled
PeepCam (TheMasterCado@PeepCam), enabled

**Comment by TheMasterCado** [comment]
Because of a problem with my notifications, I did not see that issue when it was created. If it's still relevant, can you tell me what you tried to do when it gave you the error ?

**Comment by sam-dyer** [comment]
As you have not updated this mod I will assume it is still a problem, unless the recent parkitect update has solved it, and all I did was use it I didn’t have to do anything for it to show the error. Also the error would constantly appear.

**Comment by TheMasterCado** [comment]
I will look into that, but it seems like you're the only one with a problem. Maybe a problem with another mod.

**Comment by sam-dyer** [comment]
I’ll have a look tomorrow and have a play around to see if I still get a issue and will tell you then.

**Comment by TheMasterCado** [comment]
Will close the issue, this looks like an isolated problem and I did not have any news since April
